### PR TITLE
Adding average_rating to an event and rating to an event comment JOINDIN-544

### PR DESCRIPTION
**Pull request by ThijsFeryn**
This commit performs the necessary changes to support event rating. This also requires changes in the API which have already been coded. The related pull request can be found here: https://github.com/joindin/joindin-api/pull/156

### CODE REVIEW

**Comment by akrabat** [comment]
ok to test

**Comment by akrabat** [comment]
Waiting on [API PR 156](https://github.com/joindin/joindin-api/pull/156)

**Comment by lornajane** [comment]
The dependent pull request for the API is now merged but this one needs some attention before it is ready.  It has failed the build (click the "details" button to see why ... the console output shows that phpcodesniffer is unhappy) and also needs rebasing by the look of it.  Can you please update and then we'll review.  Thanks!

**Comment by ThijsFeryn** [comment]
@lornajane Fixed the PHPCS stuff and the build no longer fails. I'm not too familiar with rebasing. Is it just a matter of executing "git rebase master" or is there more to it?

**Comment by ThijsFeryn** [comment]
@lornajane Is the rebase complete? It got pretty messy, hope I got it all covered.

**Comment by akrabat** [comment]
I'll review when I can.

**Comment by akrabat** [comment]
I couldn't get this to work locally, so I took the relevant bits and put them into #220.

**Pull request closed without merging**
