### PR TITLE
JOINDIN-575 [WIP] Validate URLs before at least displaying them, better before storing

### PR DESCRIPTION
**Pull request by shaunmza**
PR for code / functionality review see https://joindin.jira.com/browse/JOINDIN-575
Added changes to try and resolve url's on saving an event.
Short url's are followed to the final url, if the url does not resolve the save fails

### CODE REVIEW

**Comment by lornajane** [comment]
ok to test

**Comment by lornajane** [comment]
I notice that this build is marked as failed, but purely because of some coding standards errors - you can see the output of the phpcs tool here: http://jenkins.joind.in/job/web2-pr-build/332/console

**Comment by akrabat** [comment]
Please remove CfP related items from this PR, including the `dateFormat` Twig function.

**Comment by lornajane** [comment]
Closing for now but feel free to re-open if you get a chance to make the requested changes.  Thanks :)

**Comment by heiglandreas** [comment]
Thank you for your contribution. Even though it took a bit longer we found nally merged your code! Thank you!

**Pull request closed without merging**
