### PR TITLE
Define whitespace

### PR DESCRIPTION
**Pull request by ericpoe**
This helps prevent and fix some instances of PSR-2 (see: #121 ) whitespace oops when editing files.

See [editorconfig](http://editorconfig.org/) for more info about this config file and the editors that support it.

### CODE REVIEW

**Comment by Jean85** [comment]
Nice PR, thanks!

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by ericpoe** [comment]
Nuts. I see what I did wrong. I'll work on it this evening.

**Comment by liam-wiltshire** [comment]
@ericpoe merging your other PR has caused a conflict - could you please rebase and resolve.

Thanks!

**Comment by ericpoe** [comment]
@liam-wiltshire rebased and resolved. Cheers.

**Pull request merged**
