### PR TITLE
Enable github login

### PR DESCRIPTION
**Pull request by exussum12**
Adds a button and the call to the API to enable github users to register
or login without an account here

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by liam-wiltshire** [comment]
Thanks for this @exussum12 - I'm waiting for https://github.com/joindin/joindin-api/pull/424 to be sorted before I merge anything else that relies on the API as that PR touches lots of files, but as soon as that's through I'll look at this

**Comment by exussum12** [comment]
I am going to update this to be id based instead of email so will need a little extra time either way

**Comment by svpernova09** [comment]
Closing as we've also put on hold adding providers until we clean up the oath code we're using

**Pull request closed without merging**
