### PR TITLE
Moves twig filters and functions into autoloadable twig extensions

### PR DESCRIPTION
**Pull request by zghosts**
This PR replaces the deprecated Twig_Filter_Function with Twig_SimpleFilter

### CODE REVIEW

**Comment by iansltx** [comment]
@zghosts Go ahead and rebase this.

**Comment by ericpoe** [comment]
@zghosts what kind of tests are the `.test` files?

**Comment by zghosts** [comment]
They are test fixtures run by the Twig_Test_IntegrationTestCase, which makes testing of twig extensions a lot easier:
https://twig.symfony.com/doc/2.x/advanced.html#testing-an-extension
they work in a similar way to how tests for PHP-src are written

**Comment by ericpoe** [comment]
Interesting. I've written phpt tests before, but I didn't recognize this usage as creating fixtures, too. https://github.com/twigphp/Twig/blob/2.x/test/Twig/Tests/Fixtures/tests/dynamic_test.test

**Pull request merged**
