### PR TITLE
JOINDIN-143 show links on talk page

### PR DESCRIPTION
**Pull request by exussum12**
image

Show all links on the talk page

### CODE REVIEW

**Comment by railto** [comment]
ok to test

**Comment by exussum12** [comment]
Is there a joindin logo I can use for the previous talks link ? Currently its re using the code link but should really be updated to be a joindin one.

**Comment by liam-wiltshire** [comment]
Really your options are:
https://joind.in/img/apple-touch-icon.png
or 
https://joind.in/favicon.ico

**Comment by liam-wiltshire** [comment]
Or shrink down this one: https://joind.in/img/event_icons/none.png

**Pull request merged**
