### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by exussum12**
Need to over ride redis and set default timezone

### CODE REVIEW

**Comment by railto** [comment]
Thank's for adding this @exussum12, quick question tho, considering we have the VM project for providing a production'ish environment, what benefit will this bring? My main concern here being that we'll be providing 2 different development environments that we'd then need to support.

**Comment by exussum12** [comment]
Docker is much quicker for linux based envs, just allowing extra choice

**Comment by EricHogue** [comment]
This PR looks good. But as for adding Docker, I think we should either migrate to Docker or stay with Vagrant. 

If we try to keep both, it means more maintenance work. It might also be overwhelming for new contributors who won't know which solution to pick.

**Comment by mcneely** [comment]
As this has no conflicts and doesn't break anything just makes the code usable for those wishing to run and test under docker, there's no reason to not merge. Doing so now.

**Pull request merged**
