### PR TITLE
Include typeahead.bundle.min.js in /web/js (fix JIRA JOINDIN-673)

### PR DESCRIPTION
**Pull request by rogeriopradoj**
https://joindin.jira.com/browse/JOINDIN-673

JOINDIN-673 #close Fixed.

### CODE REVIEW

**Comment by lornajane** [comment]
ok to test

**Comment by lornajane** [comment]
Thanks for the quick fix, much appreciated :)

**Comment by rogeriopradoj** [comment]
Hey, @lornajane , my pleasure!

**Comment by rogeriopradoj** [comment]
@lornajane , maybe it's not the best place to talk about it, LOL, but I made a bet with a friend of mine, @ivanrosolen (we both are part of @phpsp :smile: , Brazil, São Paulo area).

So, I said that the former joind.in was built on CodeIgniter Framework, showed him the code in GitHub repository, but he said I just could won the bet (in time, the winner would get some beers) if @lornajane herself confirm that statement.

Please, help me! :smile_cat: :smile_cat: :smile_cat:

**Comment by akrabat** [comment]
@rogeriopradoj, @ivanrosolen: You can tell by inspection of publicly available source code! 

This is the source code for the legacy website: https://github.com/joindin/joind.in. As you can [see](https://github.com/joindin/joind.in/blob/master/src/system/codeigniter/CodeIgniter.php#L31), it's a CodeIgniter project.

**Comment by rogeriopradoj** [comment]
Yeah!!! I'll have some drinks by @ivanrosolen!!

Thanks @lornajane @akrabat. When you get in Brazil/São Paulo some day please let me pay a drink for you two!

**Pull request merged**
