### PR TITLE
Listing 5 hot events on the about and apps page.

### PR DESCRIPTION
**Pull request by phpetra**
Created a separate twig template for the event list

### CODE REVIEW

**Comment by lornajane** [comment]
I think start should be 0 rather than 1, it seems to miss off the hottest event

**Comment by phpetra** [comment]
Fixed it now (and checked).
Sorry for not paying enough attention last night.

**Comment by lornajane** [comment]
Bother I merged this without realising the build hadn't run and it failed.

**Comment by lornajane** [comment]
ok to test

**Pull request merged**
