### PR TITLE
Joindin 518

### PR DESCRIPTION
**Pull request by pavlakis**
* Added message above the box: "Please log in to comment on this event."
* If login fails, redirect back to the event where the form was completed and show the error message there.

### CODE REVIEW

**Comment by lornajane** [comment]
ok to test

**Comment by lornajane** [comment]
add to whitelist

**Comment by lornajane** [comment]
Couple of things to look at before we can merge this.  Firstly: the build failed, just on coding standards, click the "Details" link on the PR on GitHub and then in Jenkins try "Console Output" to see what happened.  You can run the codesniffer stuff locally by running "phing phpcs" from the root of the project.

Also, more importantly, when I don't log in correctly, I don't get any feedback.  I *should* be sent to the login form (i.e. the /login page) and see an error message.  Then when I do log in correctly, I should come back to the talk or event I was originally trying to log in on.  Does that make sense?

**Comment by heiglandreas** [comment]
makes perfect sense! And I HATE coding standards ;-) I always manage to break them....

**Comment by akrabat** [comment]
@pavlakis Have you had a chance to look at this again yet?

**Comment by akrabat** [comment]
Closing due to inactivity

**Pull request closed without merging**
