### PR TITLE
Joindin 616 - Move "attending event" button and associated issues

### PR DESCRIPTION
**Pull request by cal-tec**
The main focus of this PR is JOINDIN-616 but this lead to other issues being discovered.

The jquery associated with the "attending event" button (on the event page) did not function correctly due to missing elements.
This was fixed by using the existing template for the attending string.

The attending string template was altered to increase re-usability

### CODE REVIEW

**Comment by lornajane** [comment]
ok to test

**Comment by cal-tec** [comment]
I cant work out why this is failing? It seems to be the ./app/src/Application/ApplicationController.php file but I have not altered this????

**Comment by lornajane** [comment]
This is my fault!  I merged a PR to master that hadn't had the build run on it somehow and it has phpcs failures in it, so master currently also fails the build.  I'm on the road a FOWA so I haven't managed to fix it yet, sorry :(

**Comment by cal-tec** [comment]
No Problems, I thought it was something I had managed to do as git is still a bit of a box of mystery to me.

**Comment by akrabat** [comment]
add to whitelist

**Comment by akrabat** [comment]
There we go :)

**Pull request merged**
