### PR TITLE
Allow clearing of CfP dates when editing an event

### PR DESCRIPTION
**Pull request by akrabat**
An empty date field is valid when we want to clear it.

### CODE REVIEW

**Comment by lornajane** [comment]
I'm able to clear the date field before I merge this change, so I'm not sure how to test this PR

**Comment by akrabat** [comment]
This is the way I tested:

```bash
# set CFP start & end dates
curl -X "PUT" "http://api.dev.joind.in/v2.1/events/3" \
    -H "Content-Type: application/json" \
    -H "Authorization: Oauth fb4daeb2556c8004" \
    -H "Accept: application/json" \
    -d $'{
  "name": "Test Event",
  "start_date": "2015-03-01",
  "end_date": "2015-03-02",
  "description": "Lorem ipsum",
  "tz_continent": "Europe",
  "tz_place": "London",
  "location": "Online",
  "cfp_start_date": "2015-02-01",
  "cfp_end_date": "2015-02-10"
}'

# check
echo "cfp_start_date & cfp_end_date should be set"
curl -s -X "GET" "http://api.dev.joind.in/v2.1/events/3?verbose=yes" \
  -H "Content-Type: application/json" \
  -H "Authorization: Oauth fb4daeb2556c8004" \
  -H "Accept: application/json" | python -mjson.tool | grep cfp



# clear CFP start & end dates
curl -X "PUT" "http://api.dev.joind.in/v2.1/events/3" \
  -H "Content-Type: application/json" \
  -H "Authorization: Oauth fb4daeb2556c8004" \
  -H "Accept: application/json" \
  -d $'{
  "name": "Test Event",
  "start_date": "2015-03-01",
  "end_date": "2015-03-02",
  "description": "Lorem ipsum",
  "tz_continent": "Europe",
  "tz_place": "London",
  "location": "Online",
  "cfp_start_date": "",
  "cfp_end_date": ""
}'

# check
echo ""
echo "cfp_start_date & cfp_end_date should be clear"
curl -s -X "GET" "http://api.dev.joind.in/v2.1/events/3?verbose=yes" \
  -H "Content-Type: application/json" \
  -H "Authorization: Oauth fb4daeb2556c8004" \
  -H "Accept: application/json" | python -mjson.tool | grep cfp
```




Running when  `master` is at commit [c80c9a1](https://github.com/joindin/joindin-api/commit/c80c9a196afce89f7373cdb92d5baf597860725f):
```
$ ./cfp-test.sh 
cfp_start_date & cfp_end_date should be set
            "cfp_end_date": "2015-02-10T00:00:00+00:00",
            "cfp_start_date": "2015-02-01T00:00:00+00:00",
            "cfp_url": "http://webconf15.example.org/cfp",

cfp_start_date & cfp_end_date should be clear
            "cfp_end_date": "2015-02-10T00:00:00+00:00",
            "cfp_start_date": "2015-02-01T00:00:00+00:00",
            "cfp_url": "http://webconf15.example.org/cfp",
```

Running when  `master` is at commit [f20306e](https://github.com/joindin/joindin-api/commit/f20306e411c836dfcdf966d1201f04812ce08a95):
```
$ ./cfp-test.sh 
cfp_start_date & cfp_end_date should be set
            "cfp_end_date": "2015-02-10T00:00:00+00:00",
            "cfp_start_date": "2015-02-01T00:00:00+00:00",
            "cfp_url": "http://webconf15.example.org/cfp",

cfp_start_date & cfp_end_date should be clear
            "cfp_end_date": null,
            "cfp_start_date": null,
            "cfp_url": "http://webconf15.example.org/cfp",
```

**Comment by lornajane** [comment]
Yes the API part works perfectly and is merged, but without changing web2, I can save empty date fields and the fields do save as empty and the event I'm editing does disappear from the open CfPs list.  So I'm not sure how to test this web2 part of the change.

**Comment by akrabat** [comment]
Sorry. I'm clearly confused about which project I'm on!

Without this PR, the `cfp_start_date` and `cfp_end_date` fields are not sent to the API when they are cleared.

Looking at my notes, I thought that this was the problem so this patch changed web2 to send empty fields in the JSON. I then subsequently discovered that this didn't work and changed api too. Then submitted both patches without checking if the web2 change was still needed.

**Comment by lornajane** [comment]
OK I'll close for now

**Pull request closed without merging**
