### PR TITLE
Add page specific <title>s

### PR DESCRIPTION
**Pull request by kazu9su**
If this approach is correct, I'll continue as same.
Please confirm my changes.

Thanks!

### CODE REVIEW

**Comment by akrabat** [comment]
Yes, that all looks fine to me.

**Comment by kazu9su** [comment]
Sorry I hadn't be able to do that because of my dad's disease. 

I start this issue again.

**Comment by akrabat** [comment]
That's okay. Open source contributions come after everything else.

**Comment by kazu9su** [comment]
Hi everyone,

Could you check my changes at once?

Thanks!

**Comment by akrabat** [comment]
Thanks. I've merged and pushed.

**Pull request closed without merging**
