### PR TITLE
Remove Facebook- and Twittter-login

### LINKED ISSUE #922: Trying to join using Twitter/Facebook
At the moment, it is not possible to join Joind using Twitter / X or Facebook. There are some buttons available at the index, but both buttons are giving errors. Twitter / X will create the app and fails afterwards. Facebook will show an error-message directly. 

Is this something, which can be fixed? If not, I guess it is better to remove both buttons.

### PR DESCRIPTION
**Pull request by Sjors1985**
This PR contains removals for Twitter / X- and Facbook-login for creating an account. Both functions aren't working properly.

Closes #922 

Sidenote: This is my first PR ever, so if you have feedback to optimize it, please let me know.

### CODE REVIEW

**Comment by heiglandreas** [comment]
This looks really goot! Thank you for your contribution.

I will give it a test oater today but do currently not see any issues.

**Comment by Sjors1985** [comment]
Hi,

I was wondering if you had already tested my code. And I also detected my commits are `Unverified`. Is that okay for you?

**Comment by heiglandreas** [comment]
The unverified is OK (After all it's only deleting code 😁)

I have not yet managed to give it a go. It's planned for this weeek 🙈

**Comment by Sjors1985** [comment]
Thanks for your response! :)

I'm going to check why my commits aren't verified

**Comment by afilina** [comment]
> It's planned for this weeek 🙈

@heiglandreas Bump.

**Review by heiglandreas — APPROVED** [review]
Should not break anything. Local tests worked fine.

**Pull request merged**
