### PR TITLE
JOINDIN-575 Added changes to try and resolve url's on saving an event.

### PR DESCRIPTION
**Pull request by heiglandreas**
Short url's are followed to the final url, if the url does not resolve the save fails

### CODE REVIEW

**Comment by heiglandreas** [comment]
This PR replaces #249.

**Comment by zghosts** [comment]
I want to say, could you please add some tests? At least for the constraints.

**Comment by heiglandreas** [comment]
I can. As this is a PR from 2015 it's unfair tonask the original contributor, so I'll see what I can do tomorrow during a train ride 😁

**Comment by zghosts** [comment]
2015? That’s old, asking the original contributer would indeed be unfair, do what you can. tests for the heavy lifting parts would be great

**Comment by heiglandreas** [comment]
Additional testing added. And some minor refactoring as well...

**Pull request merged**
